package GUIQytetet;

import java.util.List;
import javax.swing.JOptionPane;
import modeloqytetet.Casilla;
import modeloqytetet.Jugador;
import modeloqytetet.MetodoSalirCarcel;
import modeloqytetet.Qytetet;

/**
 *
 * @author cadid
 */
public class ControladorQytetet extends javax.swing.JFrame {

    private Qytetet juego;
    private Jugador jugador;
    private Casilla casilla;
    private static ControladorQytetet instance;
    
    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        instance = this;
        initComponents();
        juego = Qytetet.getInstance();
        
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(this, true);
        List<String> nombres = capturaNombres.obtenerNombres();
        
        juego.inicializarJuego(nombres);
        Dado.createInstance(instance);
        
        actualizar(juego);
        this.jTabbedPanel.setEnabledAt(1, false);
    }
    
    public static ControladorQytetet getInstance() {
        return instance;
    }
    
    public static void mostrar(String str) {
        JOptionPane.showMessageDialog(null, str, "Qytetet info", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizar(Qytetet qytetet) {
        juego = qytetet;
        
        jugador = juego.getJugadorActual();
        casilla = jugador.getCasillaActual();
        
        vistaQytetet.actualizar(jugador.toString(), casilla.toString(), juego.getSorpresaActual() != null ? juego.getSorpresaActual().toString() : null);
        vistaGestiones.actualizar(jugador.getPropiedades());
        
        if (jugador.getEncarcelado()) {
            jbSalirDado.setEnabled(!jbSalirDado.isEnabled()); //si ya están activados, desactivar y pasar turno. De lo contrario sólo puedes intentar salir
            jbSalirPagando.setEnabled(!jbSalirPagando.isEnabled());
            jbJugar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSalirDado = new javax.swing.JButton();
        jbSalirPagando = new javax.swing.JButton();
        jbSiguienteJugador = new javax.swing.JButton();
        jbAplicarSorpresa = new javax.swing.JButton();
        jbComprarPropiedad = new javax.swing.JButton();
        jbJugar = new javax.swing.JButton();
        jbGestionInmobiliaria = new javax.swing.JButton();
        jTabbedPanel = new javax.swing.JTabbedPane();
        vistaQytetet = new GUIQytetet.VistaQytetet();
        vistaGestiones = new GUIQytetet.VistaGestionInmobiliaria();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbSalirDado.setText("Salir cárcel con dado");
        jbSalirDado.setEnabled(false);
        jbSalirDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirDadoActionPerformed(evt);
            }
        });

        jbSalirPagando.setText("Salir cárcel pagando");
        jbSalirPagando.setEnabled(false);
        jbSalirPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirPagandoActionPerformed(evt);
            }
        });

        jbSiguienteJugador.setText("Siguiente Jugador");
        jbSiguienteJugador.setEnabled(false);
        jbSiguienteJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteJugadorActionPerformed(evt);
            }
        });

        jbAplicarSorpresa.setText("Aplicar Sorpresa");
        jbAplicarSorpresa.setEnabled(false);
        jbAplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAplicarSorpresaActionPerformed(evt);
            }
        });

        jbComprarPropiedad.setText("Comprar Propiedad");
        jbComprarPropiedad.setEnabled(false);
        jbComprarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarPropiedadActionPerformed(evt);
            }
        });

        jbJugar.setText("Jugar");
        jbJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJugarActionPerformed(evt);
            }
        });

        jbGestionInmobiliaria.setText("Gestión inmobiliaria");
        jbGestionInmobiliaria.setEnabled(false);
        jbGestionInmobiliaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionInmobiliariaActionPerformed(evt);
            }
        });

        jTabbedPanel.addTab("Resumen", vistaQytetet);
        jTabbedPanel.addTab("Gestiones", vistaGestiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalirDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSalirPagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addComponent(jbJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbGestionInmobiliaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbComprarPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAplicarSorpresa)
                .addGap(18, 18, 18)
                .addComponent(jbSiguienteJugador)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSiguienteJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAplicarSorpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSalirDado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalirPagando)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbComprarPropiedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbGestionInmobiliaria)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jbSalirDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirDadoActionPerformed
        intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
    }//GEN-LAST:event_jbSalirDadoActionPerformed

    private void intentarSalirCarcel(MetodoSalirCarcel metodo) {
        boolean sale = juego.intentarSalirCarcel(metodo);
        if (sale) {
            mostrar("Has salido de la cárcel. Ahora puedes seguir jugando");
            this.jbSalirDado.setEnabled(false);
            this.jbSalirPagando.setEnabled(false);
            this.jbJugar.setEnabled(true);
        } else {
            mostrar("No has podido salir de la cárcel. Se pasa el turno");
            finTurno();
        }
    }
    
    private void jbJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJugarActionPerformed
        this.jbJugar.setEnabled(false);
        boolean tienePropietario = juego.jugar();
        
        switch (jugador.getCasillaActual().getTipo()) {
            case SORPRESA:
                mostrar(juego.getSorpresaActual().toString());
                
                this.jbAplicarSorpresa.setEnabled(true);     
                break;
            case CALLE:
                if (tienePropietario) {
                    mostrar("Has caído en una casilla con propietario");
                } else {
                    mostrar("Esta casila no tiene propietario");
                    this.jbComprarPropiedad.setEnabled(true);
                    
                    finTurno();
                }
                break;
            case JUEZ:
                mostrar("El juez te ha mando a la cárcel");
            case PARKING:
            case IMPUESTO:
            case SALIDA:
            case CARCEL:
                finTurno();
                break;
        }
        actualizar(juego);
    }//GEN-LAST:event_jbJugarActionPerformed

    private void jbAplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAplicarSorpresaActionPerformed
        this.jbAplicarSorpresa.setEnabled(false);
        boolean nuevaCasillaPropietario = juego.aplicarSorpresa();
        if (nuevaCasillaPropietario) {
            mostrar("Has caído en una propiedad con propietario y has pagado su alquiler");
        }
        finTurno();
    }//GEN-LAST:event_jbAplicarSorpresaActionPerformed

    private void jbComprarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarPropiedadActionPerformed
        this.jbComprarPropiedad.setEnabled(false);
        boolean puedoComprar = juego.comprarTituloPropiedad();
        if (puedoComprar) {
            mostrar("Has comprado la casilla " + jugador.getCasillaActual().getNumeroCasilla());
        } else {
            mostrar("No puedes comprar la casilla " + jugador.getCasillaActual().getNumeroCasilla());
        }
        finTurno();
    }//GEN-LAST:event_jbComprarPropiedadActionPerformed

    private void jbSiguienteJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteJugadorActionPerformed
        this.jbSiguienteJugador.setEnabled(false);
        if (jugador.getSaldo() <= 0) {
            // bancarrota
            mostrar("Ha terminado el juego porque " + jugador.getName() + " ha caído en bancarrota");
            
            this.jbJugar.setEnabled(false);
        } else {
            // gestionar final de turno
            jugador = juego.siguienteJugador();
            casilla = jugador.getCasillaActual();
            
            this.jbJugar.setEnabled(true);
            this.jbComprarPropiedad.setEnabled(false);
            this.jbGestionInmobiliaria.setEnabled(false);
            this.jTabbedPanel.setEnabledAt(1, false);
            this.jbAplicarSorpresa.setEnabled(false);
            this.jbSalirDado.setEnabled(false);
            this.jbSalirPagando.setEnabled(false);
            this.jTabbedPanel.setSelectedIndex(0);
        }
        this.actualizar(juego);
    }//GEN-LAST:event_jbSiguienteJugadorActionPerformed

    private void jbSalirPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirPagandoActionPerformed
        intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
    }//GEN-LAST:event_jbSalirPagandoActionPerformed

    private void jbGestionInmobiliariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionInmobiliariaActionPerformed
        this.jTabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_jbGestionInmobiliariaActionPerformed

    public void finGestion() {
        this.jbGestionInmobiliaria.setEnabled(false);
        this.jTabbedPanel.setEnabledAt(1, false);
        this.jTabbedPanel.setSelectedIndex(0);
    }
    
    private void finTurno() {
        if (jugador.tengoPropiedades() && !jugador.getEncarcelado() && jugador.getSaldo() > 0) {
            this.jbGestionInmobiliaria.setEnabled(true);
            this.jTabbedPanel.setEnabledAt(1, true);
        }
        
        this.jbSiguienteJugador.setEnabled(true);
        this.actualizar(juego);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        ControladorQytetet controladorQytetet = new ControladorQytetet();
        controladorQytetet.setTitle("Qytetet");
        controladorQytetet.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JButton jbAplicarSorpresa;
    private javax.swing.JButton jbComprarPropiedad;
    private javax.swing.JButton jbGestionInmobiliaria;
    private javax.swing.JButton jbJugar;
    private javax.swing.JButton jbSalirDado;
    private javax.swing.JButton jbSalirPagando;
    private javax.swing.JButton jbSiguienteJugador;
    private GUIQytetet.VistaGestionInmobiliaria vistaGestiones;
    private GUIQytetet.VistaQytetet vistaQytetet;
    // End of variables declaration//GEN-END:variables
}
